# Copyright 2019-2024 Tauri Programme within The Commons Conservancy
# SPDX-License-Identifier: Apache-2.0
# SPDX-License-Identifier: MIT

---
name: 📚 Docs Report
about: Create a report to help us improve the docs
title: "[docs] "
labels: 'type: documentation'
assignees: ''

---